const data = [
  {
    Attack_Id: 1,
    Attack_name: "Romance Scame",
    Attack_Category: "Cybersecurity",
    Date_of_Attack: "2021-02-20T19:00:00.000Z",
    Lost_Amount: "3.4$",
    Attack_KeyPoints: {
      0: "money apps 2020 need individual needing number older story sent",
      1: "romance reported losses money individual scams older reads aged people",
      2: "opportunity individual losses money romance reports number scams reason sent",
      3: "need increased dating losses media place scams reported reports period",
      4: "reported record report online money phony ftc social romance reports",
      5: "platforms media scammers opportunity reported needs place photos reality older",
      6: "media 2020 ftc individual sent place opportunities story scams reached",
      7: "romance money scams dating losses report love people ftc victims",
      8: "individual older record story sent excuses victims period online fraud",
      9: "nearly opportunities fraud reached report dating needing online 2020 social",
    },
    Summary:
      "<p>As dating apps experience a boom amid COVID-19, losses to romance scams soar too</p>",
    Counter_Measures: null,
    Longitude: "3.7492",
    Latitude: "40.4637",
    Country: "Pakistan",
    City: null,
    Type_of_Org: "Private",
    Title_of_Org: "FTC",
    Author_Name: "Amer Owaida",
    Link: "https://www.welivesecurity.com/2021/02/16/romance-scams-2020-breaking-hearts-wallets-records/",
    Access_Date: null,
  },
  {
    Attack_Id: 4,
    Attack_name: "Beaware of COVID",
    Attack_Category: "Cybersecurity",
    Date_of_Attack: "2021-02-10T19:00:00.000Z",
    Lost_Amount: null,
    Attack_KeyPoints: {
      0: "email vaccines 19 scam various covid does vaccine just real",
      1: "riddled emails just partners internet cdc organization don falsehoods signs",
      2: "links emails end scam fake scammers involved payment spam signs",
      3: "email health details end example signs need scam riddled manufacture",
      4: "pharmaceutical riddled lacks real mistakes scam efforts vaccines tactic manufacture",
      5: "new example scrutinize links riddled information need narrative patent just",
      6: "example 19 efforts emails spam need like vaccines signs pandemic",
      7: "payment email scammers organization scrutinize emails enterprising need vaccine signs",
      8: "emails just pharmaceutical vaccines spam does various manufacture lacks don",
      9: "like falsehoods don email 19 real pandemic scam internet various",
    },
    Summary:
      "<p>The vaccination push provides a vital shot in the arm for the worldâ€™s battle against the pandemic, but it's also a topic ripe for exploitation by fraudsters and purveyors of misinformation</p>",
    Counter_Measures: null,
    Longitude: -100.4458825,
    Latitude: 39.7837304,
    Country: "USA",
    City: null,
    Type_of_Org: "Private",
    Title_of_Org: "WHO",
    Author_Name: "Amer Owaida",
    Link: "https://www.welivesecurity.com/2021/02/16/beware-covid19-vaccine-scams-misinformation/",
    Access_Date: null,
  },
  {
    Attack_Id: 2,
    Attack_name: "Memon",
    Attack_Category: "Malware",
    Date_of_Attack: "2021-02-15T19:00:00.000Z",
    Lost_Amount: null,
    Attack_KeyPoints: "a-z",
    Summary: "a-z",
    Counter_Measures: null,
    Longitude: 105.3188,
    Latitude: 61.524,
    Country: "USA",
    City: null,
    Type_of_Org: "Bank",
    Title_of_Org: null,
    Author_Name: null,
    Link: null,
    Access_Date: null,
  },
  {
    Attack_Id: 5,
    Attack_name: "Romance Scame",
    Attack_Category: "Social Media",
    Date_of_Attack: "2021-02-05T19:00:00.000Z",
    Lost_Amount: "3.4$",
    Attack_KeyPoints: {
      0: "money apps 2020 need individual needing number older story sent",
      1: "romance reported losses money individual scams older reads aged people",
      2: "opportunity individual losses money romance reports number scams reason sent",
      3: "need increased dating losses media place scams reported reports period",
      4: "reported record report online money phony ftc social romance reports",
      5: "platforms media scammers opportunity reported needs place photos reality older",
      6: "media 2020 ftc individual sent place opportunities story scams reached",
      7: "romance money scams dating losses report love people ftc victims",
      8: "individual older record story sent excuses victims period online fraud",
      9: "nearly opportunities fraud reached report dating needing online 2020 social",
    },
    Summary:
      "<p>As dating apps experience a boom amid COVID-19, losses to romance scams soar too</p>",
    Counter_Measures: null,
    Longitude: 30.5595,
    Latitude: 22.9375,
    Country: "USA",
    City: null,
    Type_of_Org: "Private",
    Title_of_Org: "FTC",
    Author_Name: "Amer Owaida",
    Link: "https://www.welivesecurity.com/2021/02/16/romance-scams-2020-breaking-hearts-wallets-records/",
    Access_Date: null,
  },

  {
    Attack_Id: 3,
    Attack_name: "Romance Scame",
    Attack_Category: "Vulnerability",
    Date_of_Attack: "2021-02-04T19:00:00.000Z",
    Lost_Amount: "3.4$",
    Attack_KeyPoints: {
      0: "money apps 2020 need individual needing number older story sent",
      1: "romance reported losses money individual scams older reads aged people",
      2: "opportunity individual losses money romance reports number scams reason sent",
      3: "need increased dating losses media place scams reported reports period",
      4: "reported record report online money phony ftc social romance reports",
      5: "platforms media scammers opportunity reported needs place photos reality older",
      6: "media 2020 ftc individual sent place opportunities story scams reached",
      7: "romance money scams dating losses report love people ftc victims",
      8: "individual older record story sent excuses victims period online fraud",
      9: "nearly opportunities fraud reached report dating needing online 2020 social",
    },
    Summary:
      "<p>As dating apps experience a boom amid COVID-19, losses to romance scams soar too</p>",
    Counter_Measures: null,
    Longitude: 69.3451,
    Latitude: 30.3753,
    Country: "USA",
    City: null,
    Type_of_Org: "Private",
    Title_of_Org: "FTC",
    Author_Name: "Amer Owaida",
    Link: "https://www.welivesecurity.com/2021/02/16/romance-scams-2020-breaking-hearts-wallets-records/",
    Access_Date: null,
  },
];
export default data;
